apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  sourceRepos:
  - git@github.com:sre2go/app-of-apps.git
  description: App of Apps project for monitoring a git repo
  roles:
  - name: admin
    policies:
    - p, applications, *, *, * # allow all actions on all applications
  - name: developer
    policies:
    - p, applications, get, *, * # allow get action on all applications
    - p, applications, create, *, * # allow create action on all applications
    - p, applications, update, *, * # allow update action on all applications
    - p, applications, sync, *, * # allow sync action on all applications
  - name: viewer
    policies:
    - p, applications, get, *, * # allow get action on all applications
