apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    helm:
      valueFile:
        - values.yaml
    path: argocd
    repoURL: git@github.com:sre2go/app-of-apps.git
    targetRevision: main
