apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: 'git@github.com:sre2go/app-of-apps.git'
    path: nginx1
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
